export default Object.freeze({
    ARTICLE_DETAIL: 'DetailScreen',
    ACCUEIL: 'AccueilScreen',
    NOTIFICATION: 'NotificationScreen',
    GIFT: 'Cadeau',
    OFFRE: 'Offre',
    FAVORIS: 'FavorisScreen',
    COMPTE: 'CompteScreen',
    LOCATION: 'LocationScreen',
    MESSAGE: 'MessageScreen',
    PARAM: 'ParametreScreen',
    FACTURE: 'FactureScreen',
    ARTICLE: 'ArticleScreen',
    CART: 'ShoppingCartScreen',
    LOGIN: 'LoginScreen',
    REGISTER: 'RegisterScreen',
    USER_INFO: 'UserInfoScreen',
    USER_NOTIF: 'UserNotifScreen',
    ORDER: 'OrderScreen',
    CATEGORIE: 'CategorieScreen',
    NEW_CATEG: 'NewCategorieScreen',
    OTHER: 'OtherFileScreen',
    PAYEMENT: 'PayementScreen',
    USER_PAYEMENT: 'UserPayementScreen',
    NEW_USER_PAYEMENT: 'NewUserPayementScreen',
    PLAN: 'PlanScreen',
    NEW_PLAN: 'NewPlanScreen',
    LIVRAISON: 'LivraisonScreen'

})